### ISSUE TITLE
what  external code you use?

### ISSUE THREAD

**Issue by Sandy4321** [mesnilgr/nbsvm#5]
os.system(trainsvm + " -s 0 train-nbsvm.txt model.logreg")

is it libsvm, if yest how to install on windows

**Comment by mesnilgr** [comment]
It uses libsvm.  I invite you to check their documentation to install this library on Window.

**Comment by Sandy4321** [comment]
great thanks for soon answer, but you use linux code to run python code and for preprocessing 
ye sit is easy to use libsvm on windows since they give executable files
but your file https://github.com/mesnilgr/nbsvm/blob/master/oh_my_go.sh causes problems
